import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Header } from "../components/Header";
import { MainSection } from "../components/Main";
import { Footer } from "../components/Footer";
import {  useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [hamburgerMenuOpen, setHamburgerMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={hamburgerMenuOpen ? "open_burger":""}>
      <main>
        <Header isOpen={hamburgerMenuOpen} setIsOpen={setHamburgerMenuOpen}/>
        <MainSection />
        <Footer />
      </main>
      </div>
    </>
  );
}